// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: api/weather/weather.proto

package weather

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWeatherRequest) Reset() {
	*x = CreateWeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeatherRequest) ProtoMessage() {}

func (x *CreateWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeatherRequest.ProtoReflect.Descriptor instead.
func (*CreateWeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{0}
}

type CreateWeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWeatherReply) Reset() {
	*x = CreateWeatherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeatherReply) ProtoMessage() {}

func (x *CreateWeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeatherReply.ProtoReflect.Descriptor instead.
func (*CreateWeatherReply) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{1}
}

type UpdateWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateWeatherRequest) Reset() {
	*x = UpdateWeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWeatherRequest) ProtoMessage() {}

func (x *UpdateWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWeatherRequest.ProtoReflect.Descriptor instead.
func (*UpdateWeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{2}
}

type UpdateWeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateWeatherReply) Reset() {
	*x = UpdateWeatherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWeatherReply) ProtoMessage() {}

func (x *UpdateWeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWeatherReply.ProtoReflect.Descriptor instead.
func (*UpdateWeatherReply) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{3}
}

type DeleteWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWeatherRequest) Reset() {
	*x = DeleteWeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeatherRequest) ProtoMessage() {}

func (x *DeleteWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeatherRequest.ProtoReflect.Descriptor instead.
func (*DeleteWeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{4}
}

type DeleteWeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWeatherReply) Reset() {
	*x = DeleteWeatherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeatherReply) ProtoMessage() {}

func (x *DeleteWeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeatherReply.ProtoReflect.Descriptor instead.
func (*DeleteWeatherReply) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{5}
}

type GetWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{6}
}

type GetWeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWeatherReply) Reset() {
	*x = GetWeatherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherReply) ProtoMessage() {}

func (x *GetWeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherReply.ProtoReflect.Descriptor instead.
func (*GetWeatherReply) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{7}
}

type ListWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWeatherRequest) Reset() {
	*x = ListWeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeatherRequest) ProtoMessage() {}

func (x *ListWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeatherRequest.ProtoReflect.Descriptor instead.
func (*ListWeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{8}
}

type ListWeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWeatherReply) Reset() {
	*x = ListWeatherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_weather_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeatherReply) ProtoMessage() {}

func (x *ListWeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeatherReply.ProtoReflect.Descriptor instead.
func (*ListWeatherReply) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{9}
}

var File_api_weather_weather_proto protoreflect.FileDescriptor

var file_api_weather_weather_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x77, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69,
	0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0xa3, 0x03, 0x0a, 0x07, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x12, 0x53, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x1e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33, 0x0a, 0x0b, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x22, 0x77, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x3b, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_weather_weather_proto_rawDescOnce sync.Once
	file_api_weather_weather_proto_rawDescData = file_api_weather_weather_proto_rawDesc
)

func file_api_weather_weather_proto_rawDescGZIP() []byte {
	file_api_weather_weather_proto_rawDescOnce.Do(func() {
		file_api_weather_weather_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_weather_weather_proto_rawDescData)
	})
	return file_api_weather_weather_proto_rawDescData
}

var file_api_weather_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_weather_weather_proto_goTypes = []interface{}{
	(*CreateWeatherRequest)(nil), // 0: api.weather.CreateWeatherRequest
	(*CreateWeatherReply)(nil),   // 1: api.weather.CreateWeatherReply
	(*UpdateWeatherRequest)(nil), // 2: api.weather.UpdateWeatherRequest
	(*UpdateWeatherReply)(nil),   // 3: api.weather.UpdateWeatherReply
	(*DeleteWeatherRequest)(nil), // 4: api.weather.DeleteWeatherRequest
	(*DeleteWeatherReply)(nil),   // 5: api.weather.DeleteWeatherReply
	(*GetWeatherRequest)(nil),    // 6: api.weather.GetWeatherRequest
	(*GetWeatherReply)(nil),      // 7: api.weather.GetWeatherReply
	(*ListWeatherRequest)(nil),   // 8: api.weather.ListWeatherRequest
	(*ListWeatherReply)(nil),     // 9: api.weather.ListWeatherReply
}
var file_api_weather_weather_proto_depIdxs = []int32{
	0, // 0: api.weather.Weather.CreateWeather:input_type -> api.weather.CreateWeatherRequest
	2, // 1: api.weather.Weather.UpdateWeather:input_type -> api.weather.UpdateWeatherRequest
	4, // 2: api.weather.Weather.DeleteWeather:input_type -> api.weather.DeleteWeatherRequest
	6, // 3: api.weather.Weather.GetWeather:input_type -> api.weather.GetWeatherRequest
	8, // 4: api.weather.Weather.ListWeather:input_type -> api.weather.ListWeatherRequest
	1, // 5: api.weather.Weather.CreateWeather:output_type -> api.weather.CreateWeatherReply
	3, // 6: api.weather.Weather.UpdateWeather:output_type -> api.weather.UpdateWeatherReply
	5, // 7: api.weather.Weather.DeleteWeather:output_type -> api.weather.DeleteWeatherReply
	7, // 8: api.weather.Weather.GetWeather:output_type -> api.weather.GetWeatherReply
	9, // 9: api.weather.Weather.ListWeather:output_type -> api.weather.ListWeatherReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_weather_weather_proto_init() }
func file_api_weather_weather_proto_init() {
	if File_api_weather_weather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_weather_weather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeatherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWeatherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWeatherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_weather_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeatherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_weather_weather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_weather_weather_proto_goTypes,
		DependencyIndexes: file_api_weather_weather_proto_depIdxs,
		MessageInfos:      file_api_weather_weather_proto_msgTypes,
	}.Build()
	File_api_weather_weather_proto = out.File
	file_api_weather_weather_proto_rawDesc = nil
	file_api_weather_weather_proto_goTypes = nil
	file_api_weather_weather_proto_depIdxs = nil
}
